# Generated by Django 6.0.3 on 2026-04-10 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=1)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('id_especie', models.ForeignKey(db_column='id_especie', on_delete=django.db.models.deletion.PROTECT, to='pacientes.especie')),
            ],
            options={
                'db_table': 'raza',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.cliente')),
                ('id_raza', models.ForeignKey(db_column='id_raza', on_delete=django.db.models.deletion.PROTECT, to='pacientes.raza')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
