# docker-compose.yml
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hematica_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  django:
    build: ./backend-django
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./backend-django:/app
      - media_data:/app/media
    environment:
      DB_HOST: db
      DB_NAME: hematica_db
      DB_USER: root
      DB_PASSWORD: root

volumes:
  db_data:
  media_data: