# Generated by Django 6.0.3 on 2026-04-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoestudio',
            name='nombre',
            field=models.CharField(help_text='Nombre del estudio. Ejemplo: Hemograma completo.', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogoestudio',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del estudio en pesos mexicanos. Ejemplo: 250.00', max_digits=8),
        ),
    ]
