# Generated by Django 6.0.3 on 2026-04-10 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_emp', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_empleado',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clinica', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=60)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('id_tipo_emp', models.ForeignKey(db_column='id_tipo_emp', on_delete=django.db.models.deletion.PROTECT, to='empleados.tipoempleado')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_vet', models.AutoField(primary_key=True, serialize=False)),
                ('curp', models.CharField(max_length=18)),
                ('cedula', models.CharField(max_length=10)),
                ('id_emp', models.OneToOneField(db_column='id_emp', on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
            ],
            options={
                'db_table': 'veterinario',
            },
        ),
    ]
