# Generated by Django 6.0.3 on 2026-04-13 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('usuarios', '0002_alter_tipousuario_descripcion_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(help_text='Dirección del empleado o de la clínica.', max_length=60),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_tipo_emp',
            field=models.ForeignKey(db_column='id_tipo_emp', help_text='Puesto del empleado en el laboratorio.', on_delete=django.db.models.deletion.PROTECT, to='empleados.tipoempleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', help_text='Usuario del sistema asociado a este empleado.', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_clinica',
            field=models.CharField(help_text='Nombre de la clínica o laboratorio donde trabaja.', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(help_text='Teléfono de contacto del empleado.', max_length=12),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='descripcion',
            field=models.CharField(help_text='Descripción de las responsabilidades del puesto.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='puesto',
            field=models.CharField(help_text='Nombre del puesto. Ejemplo: Recepcionista, Laboratorista.', max_length=50),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cedula',
            field=models.CharField(help_text='Cédula profesional del veterinario.', max_length=10),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='curp',
            field=models.CharField(help_text='CURP del veterinario. 18 caracteres.', max_length=18),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='id_emp',
            field=models.OneToOneField(db_column='id_emp', help_text='Empleado asociado a este veterinario.', on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
    ]
