# Generated by Django 6.0.3 on 2026-04-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_direccion_alter_empleado_id_tipo_emp_and_more'),
        ('pacientes', '0002_alter_cliente_genero_alter_cliente_id_usuario_and_more'),
        ('usuarios', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_tipo_emp',
            field=models.ForeignKey(db_column='id_tipo_emp', on_delete=django.db.models.deletion.PROTECT, to='empleados.tipoempleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre_clinica',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoempleado',
            name='puesto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='curp',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='id_emp',
            field=models.OneToOneField(db_column='id_emp', on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado'),
        ),
        migrations.CreateModel(
            name='VeterinarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='pacientes.cliente')),
                ('id_vet', models.ForeignKey(db_column='id_vet', on_delete=django.db.models.deletion.CASCADE, to='empleados.veterinario')),
            ],
            options={
                'db_table': 'veterinario_cliente',
                'unique_together': {('id_vet', 'id_cliente')},
            },
        ),
        migrations.AddField(
            model_name='veterinario',
            name='clientes',
            field=models.ManyToManyField(blank=True, help_text='Clientes asignados a este veterinario', related_name='veterinarios', through='empleados.VeterinarioCliente', to='pacientes.cliente'),
        ),
    ]
