# Generated by Django 6.0.3 on 2026-04-10 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('num_tel', models.CharField(max_length=12)),
                ('id_tipo_usuario', models.ForeignKey(db_column='id_tipo_usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipousuario')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
