# Generated by Django 6.0.3 on 2026-04-16 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='descripcion',
            field=models.CharField(help_text='Nombre del rol. Ejemplo: Cliente, Veterinario, Admin.', max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(help_text='Correo electrónico único. Se usa para iniciar sesión.', max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(db_column='id_tipo_usuario', help_text='Rol del usuario en el sistema.', on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipousuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del usuario.', max_length=80),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_tel',
            field=models.CharField(help_text='Número de teléfono de contacto.', max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='Contraseña cifrada con bcrypt. Nunca se guarda en texto plano.', max_length=60),
        ),
    ]
