# Generated by Django 6.0.3 on 2026-04-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_tipousuario_descripcion_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(help_text='Contraseña cifrada con bcrypt. Nunca se guarda en texto plano.', max_length=128),
        ),
    ]
