# Generated by Codex on 2026-05-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='id_actor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'auditoria',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(default='info', max_length=30)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id_reset', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=120, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'password_reset_token',
                'ordering': ['-creado_en'],
            },
        ),
    ]
