# Generated by Django 6.0.3 on 2026-04-16 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0002_alter_tipousuario_descripcion_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(help_text='Género del cliente. M = Masculino, F = Femenino.', max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', help_text='Usuario del sistema asociado a este cliente.', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(help_text='Nombre de la especie. Ejemplo: Canino, Felino.', max_length=25),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(help_text='Edad de la mascota en años.'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', help_text='Tutor o dueño de esta mascota.', on_delete=django.db.models.deletion.PROTECT, to='pacientes.cliente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_raza',
            field=models.ForeignKey(db_column='id_raza', help_text='Raza de la mascota. A través de la raza se obtiene la especie.', on_delete=django.db.models.deletion.PROTECT, to='pacientes.raza'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(help_text='Nombre de la mascota. Ejemplo: Firulais, Luna.', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(help_text='Sexo de la mascota. M = Macho, H = Hembra.', max_length=1),
        ),
        migrations.AlterField(
            model_name='raza',
            name='id_especie',
            field=models.ForeignKey(db_column='id_especie', help_text='Especie a la que pertenece esta raza.', on_delete=django.db.models.deletion.PROTECT, to='pacientes.especie'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='nombre',
            field=models.CharField(help_text='Nombre de la raza. Ejemplo: Labrador, Siamés.', max_length=30),
        ),
    ]
