# Generated by Django 6.0.3 on 2026-04-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_cliente_genero_alter_cliente_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cartilla_pdf',
            field=models.FileField(blank=True, help_text='Cartilla de vacunación en PDF.', null=True, upload_to='cartillas/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_raza',
            field=models.ForeignKey(db_column='id_raza', help_text='Raza de la mascota.', on_delete=django.db.models.deletion.PROTECT, to='pacientes.raza'),
        ),
    ]
