# Generated by Django 6.0.3 on 2026-04-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_cartilla_pdf_alter_paciente_id_raza'),
    ]

    operations = [
    ]
