# Generated by Django 6.0.3 on 2026-04-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_add_cartilla_pdf'),
        ('usuarios', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso de la mascota en kg.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_usuario',
            field=models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.cliente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_raza',
            field=models.ForeignKey(db_column='id_raza', on_delete=django.db.models.deletion.PROTECT, to='pacientes.raza'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='raza',
            name='id_especie',
            field=models.ForeignKey(db_column='id_especie', on_delete=django.db.models.deletion.PROTECT, to='pacientes.especie'),
        ),
        migrations.AlterField(
            model_name='raza',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
