# Generated by Django 6.0.3 on 2026-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_peso_alter_cliente_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='anamnesis',
            field=models.TextField(blank=True, help_text='Historia clínica y síntomas previos del paciente.', null=True),
        ),
    ]
