# Generated by Django 6.0.3 on 2026-04-16 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_direccion_alter_empleado_id_tipo_emp_and_more'),
        ('estudios', '0002_alter_catalogoestudio_nombre_and_more'),
        ('pacientes', '0002_alter_cliente_genero_alter_cliente_id_usuario_and_more'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='diagnostico',
            field=models.CharField(help_text='Diagnóstico del veterinario basado en los resultados.', max_length=400),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que se registró este expediente. Se genera automáticamente.'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', help_text='Mascota a la que pertenece este expediente.', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='notas',
            field=models.CharField(blank=True, help_text='Notas adicionales del veterinario. Ejemplo: Revisión en 30 días.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='tratamiento',
            field=models.CharField(blank=True, help_text='Tratamiento recomendado por el veterinario.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='fecha_muestra',
            field=models.DateTimeField(help_text='Fecha y hora en que se tomó la muestra.'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='id_solicitud',
            field=models.OneToOneField(db_column='id_solicitud', help_text='Solicitud a la que corresponden estos resultados.', on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='id_vet',
            field=models.ForeignKey(db_column='id_vet', help_text='Veterinario que procesó la muestra y registró los resultados.', on_delete=django.db.models.deletion.PROTECT, to='empleados.veterinario'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Observaciones generales del veterinario sobre la muestra.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='reporte_clinico',
            field=models.TextField(help_text='Reporte clínico completo con todos los valores obtenidos del análisis.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('muestra_recibida', 'Muestra recibida'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual de la solicitud en el flujo de atención.', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el tutor creó la solicitud. Se genera automáticamente.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', help_text='Mascota para la que se solicita el estudio.', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='notas_cliente',
            field=models.TextField(blank=True, help_text='Observaciones del tutor sobre la mascota. Ejemplo: No ha comido desde ayer.', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='id_catalogo',
            field=models.ForeignKey(db_column='id_catalogo', help_text='Tipo de estudio solicitado del catálogo.', on_delete=django.db.models.deletion.PROTECT, to='estudios.catalogoestudio'),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='id_solicitud',
            field=models.ForeignKey(db_column='id_solicitud', help_text='Solicitud a la que pertenece este estudio.', on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud'),
        ),
    ]
