# Generated by Django 6.0.3 on 2026-04-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_direccion_alter_empleado_id_tipo_emp_and_more'),
        ('estudios', '0002_alter_catalogoestudio_nombre_and_more'),
        ('solicitudes', '0002_alter_historialclinico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoestudio',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF con los resultados del estudio.', null=True, upload_to='resultados/'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='diagnostico',
            field=models.CharField(help_text='Diagnostico del veterinario basado en los resultados.', max_length=400),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, help_text='Fecha en que se registro este expediente.'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='notas',
            field=models.CharField(blank=True, help_text='Notas adicionales del veterinario.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='fecha_muestra',
            field=models.DateTimeField(help_text='Fecha y hora en que se tomo la muestra.'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='id_vet',
            field=models.ForeignKey(db_column='id_vet', help_text='Veterinario que proceso la muestra.', on_delete=django.db.models.deletion.PROTECT, to='empleados.veterinario'),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='observaciones',
            field=models.CharField(blank=True, help_text='Observaciones generales del veterinario.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoestudio',
            name='reporte_clinico',
            field=models.TextField(help_text='Reporte clinico completo con todos los valores obtenidos.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('muestra_recibida', 'Muestra recibida'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='Estado actual de la solicitud en el flujo de atencion.', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el tutor creo la solicitud.'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='notas_cliente',
            field=models.TextField(blank=True, help_text='Observaciones del tutor sobre la mascota.', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudestudio',
            name='id_catalogo',
            field=models.ForeignKey(db_column='id_catalogo', help_text='Tipo de estudio solicitado del catalogo.', on_delete=django.db.models.deletion.PROTECT, to='estudios.catalogoestudio'),
        ),
    ]
