# Generated by Django 6.0.4 on 2026-04-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_resultadoestudio_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo por el que el administrador cancelo la solicitud.', null=True),
        ),
    ]
