# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_motivo_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(
                choices=[
                    ('pendiente', 'Pendiente'),
                    ('en_proceso', 'En proceso'),
                    ('muestra_recibida', 'Muestra recibida'),
                    ('resultado_cargado', 'Resultado cargado'),
                    ('finalizado', 'Finalizado'),
                    ('rechazado', 'Rechazado'),
                    ('cancelado', 'Cancelado'),
                ],
                default='pendiente',
                help_text='Estado actual de la solicitud en el flujo de atencion.',
                max_length=20,
            ),
        ),
    ]
