# Generated by Django 6.0.3 on 2026-04-10 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('estudios', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_exp', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('diagnostico', models.CharField(max_length=400)),
                ('tratamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.CharField(blank=True, max_length=100, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'historial_clinico',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('muestra_recibida', 'Muestra recibida'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('notas_cliente', models.TextField(blank=True, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEstudio',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_muestra', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('reporte_clinico', models.TextField()),
                ('id_vet', models.ForeignKey(db_column='id_vet', on_delete=django.db.models.deletion.PROTECT, to='empleados.veterinario')),
                ('id_solicitud', models.OneToOneField(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'resultado_estudio',
            },
        ),
        migrations.CreateModel(
            name='SolicitudEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catalogo', models.ForeignKey(db_column='id_catalogo', on_delete=django.db.models.deletion.PROTECT, to='estudios.catalogoestudio')),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.PROTECT, to='solicitudes.solicitud')),
            ],
            options={
                'db_table': 'solicitud_estudio',
            },
        ),
    ]
