# Generated by Django 6.0.3 on 2026-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEstudio',
            fields=[
                ('id_catalogo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'catalogo_estudio',
            },
        ),
    ]
